/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tdata.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tdata.pb-c.h"

void data_type__init
        (DataType *message) {
    static const DataType init_value = DATA_TYPE__INIT;
    *message = init_value;
}

size_t data_type__get_packed_size
        (const DataType *message) {
    assert(message->base.descriptor == &data_type__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t data_type__pack
        (const DataType *message,
         uint8_t *out) {
    assert(message->base.descriptor == &data_type__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t data_type__pack_to_buffer
        (const DataType *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &data_type__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

DataType *
data_type__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (DataType *)
            protobuf_c_message_unpack(&data_type__descriptor,
                                      allocator, len, data);
}

void data_type__free_unpacked
        (DataType *message,
         ProtobufCAllocator *allocator) {
    if (!message)
        return;
    assert(message->base.descriptor == &data_type__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

void trace_type__init
        (TraceType *message) {
    static const TraceType init_value = TRACE_TYPE__INIT;
    *message = init_value;
}

size_t trace_type__get_packed_size
        (const TraceType *message) {
    assert(message->base.descriptor == &trace_type__descriptor);
    return protobuf_c_message_get_packed_size((const ProtobufCMessage *) (message));
}

size_t trace_type__pack
        (const TraceType *message,
         uint8_t *out) {
    assert(message->base.descriptor == &trace_type__descriptor);
    return protobuf_c_message_pack((const ProtobufCMessage *) message, out);
}

size_t trace_type__pack_to_buffer
        (const TraceType *message,
         ProtobufCBuffer *buffer) {
    assert(message->base.descriptor == &trace_type__descriptor);
    return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *) message, buffer);
}

TraceType *
trace_type__unpack
        (ProtobufCAllocator *allocator,
         size_t len,
         const uint8_t *data) {
    return (TraceType *)
            protobuf_c_message_unpack(&trace_type__descriptor,
                                      allocator, len, data);
}

void trace_type__free_unpacked
        (TraceType *message,
         ProtobufCAllocator *allocator) {
    if (!message)
        return;
    assert(message->base.descriptor == &trace_type__descriptor);
    protobuf_c_message_free_unpacked((ProtobufCMessage *) message, allocator);
}

static const ProtobufCFieldDescriptor data_type__field_descriptors[7] =
        {
                {
                        "logid",
                        1,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(DataType, logid),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "function",
                        2,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(DataType, function),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "cost",
                        3,
                        PROTOBUF_C_LABEL_REQUIRED,
                        PROTOBUF_C_TYPE_INT32,
                        0,   /* quantifier_offset */
                        offsetof(DataType, cost),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "lineno",
                        4,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_INT32,
                        offsetof(DataType, has_lineno),
                        offsetof(DataType, lineno),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "filename",
                        5,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(DataType, filename),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "input",
                        6,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(DataType, input),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
                {
                        "return",
                        7,
                        PROTOBUF_C_LABEL_OPTIONAL,
                        PROTOBUF_C_TYPE_STRING,
                        0,   /* quantifier_offset */
                        offsetof(DataType, return_),
                        NULL,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned data_type__field_indices_by_name[] = {
        2,   /* field[2] = cost */
        4,   /* field[4] = filename */
        1,   /* field[1] = function */
        5,   /* field[5] = input */
        3,   /* field[3] = lineno */
        0,   /* field[0] = logid */
        6,   /* field[6] = return */
};
static const ProtobufCIntRange data_type__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 7}
        };
const ProtobufCMessageDescriptor data_type__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "DataType",
                "DataType",
                "DataType",
                "",
                sizeof(DataType),
                7,
                data_type__field_descriptors,
                data_type__field_indices_by_name,
                1, data_type__number_ranges,
                (ProtobufCMessageInit) data_type__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
static const ProtobufCFieldDescriptor trace_type__field_descriptors[1] =
        {
                {
                        "trace",
                        1,
                        PROTOBUF_C_LABEL_REPEATED,
                        PROTOBUF_C_TYPE_MESSAGE,
                        offsetof(TraceType, n_trace),
                        offsetof(TraceType, trace),
                        &data_type__descriptor,
                        NULL,
                        0,             /* flags */
                        0, NULL, NULL    /* reserved1,reserved2, etc */
                },
        };
static const unsigned trace_type__field_indices_by_name[] = {
        0,   /* field[0] = trace */
};
static const ProtobufCIntRange trace_type__number_ranges[1 + 1] =
        {
                {1, 0},
                {0, 1}
        };
const ProtobufCMessageDescriptor trace_type__descriptor =
        {
                PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
                "TraceType",
                "TraceType",
                "TraceType",
                "",
                sizeof(TraceType),
                1,
                trace_type__field_descriptors,
                trace_type__field_indices_by_name,
                1, trace_type__number_ranges,
                (ProtobufCMessageInit) trace_type__init,
                NULL, NULL, NULL    /* reserved[123] */
        };
